TaccomStrike.Web/Controllers/ForumTopicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AvaNet.DataAccessLayer;
using AvaNet.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace AvaNet.Controllers
{
    public class ForumTopicsController : Controller
    {
        private readonly IForumTopicRepository forumTopicRepository;

        private readonly IForumThreadRepository forumThreadRepository;

        public ForumTopicsController(IForumTopicRepository forumTopicRepository, IForumThreadRepository forumThreadRepository)
        {
            this.forumTopicRepository = forumTopicRepository;
            this.forumThreadRepository = forumThreadRepository;
        }

        public IActionResult Index()
        {
            ViewData["Message"] = "This is the forum page";

            return View(forumTopicRepository.GetAll());
        }

        public IActionResult Details(int ID)
        {
            //Retrieve the forum topic corresponding to id
            ForumTopic forumTopic = forumTopicRepository.Find(ID, true);
            return View(forumTopic);
        }
    }
}

TaccomStrike.Web/Controllers/GameLoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AvaNet.DataAccessLayer;
using AvaNet.Models;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace AvaNet.Controllers
{
    public class GameLoresController : Controller
    {

        private readonly IGameLoreRepository gameLoreRepository;

        public GameLoresController(IGameLoreRepository gameLoreRepository)
        {
            this.gameLoreRepository = gameLoreRepository;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View(gameLoreRepository.GetAll());
        }

        public IActionResult Details(int ID)
        {
            return View(gameLoreRepository.Find(ID));
        }

        [Authorize(Roles = "Administrator,Moderator")]
        public IActionResult Edit(int ID)
        {
            return View(gameLoreRepository.Find(ID));
        }

        [HttpPost]
        [Authorize(Roles = "Administrator,Moderator")]
        public IActionResult Edit([Bind ("Title, ImageURL, Content")] GameLore gameLore)
        {
            gameLoreRepository.Update(gameLore);
            return RedirectToAction("Index/" + gameLore.GameLoreID);
        }
    }
}

TaccomStrike.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AvaNet</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/MyStyleSheet.css" />

        <link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet">
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/MyStyleSheet.css" asp-append-version="true" />

        <link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet">
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Download" class="navbar-brand">Play</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="GameLores" asp-action="Index">Game Lore</a></li>
                    <li><a asp-area="" asp-controller="ForumTopics" asp-action="Index">Forum</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    <div class="myFooter">
        <div class="gap"></div>
        <hr />
        <footer>
            <p>&copy; 2017 - AvaNet</p>
        </footer>
    </div>
    
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>