TaccomStrike.Web/Models/Forum/ForumThread.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace AvaNet.Models
{
    public class ForumThread
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ForumThreadID { get; set; }

        [Required]
        [StringLength(60, ErrorMessage = "Title cannot be longer than 300 characters.")]
        public string Title { get; set; }

        [Required]
        public string Content { get; set; }

        public DateTime ForumThreadCreationTime { get; set; }
        
        public ApplicationUser ApplicationUser { get; set; }

        public int ForumTopicID { get; set; }
        public ForumTopic ForumTopic { get; set; }

        public ICollection<ForumComment> ForumComments { get; set; }

        public ICollection<ForumLike> ForumLikes { get; set; }

        public bool IsBanned { get; set; }

    }
}

TaccomStrike.Web/Controllers/ForumThreadsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AvaNet.Models;
using AvaNet.DataAccessLayer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using System.Text.Encodings.Web;
using AvaNet.Services;
using AvaNet.Models.ViewModels.ForumViewModels;
using System.Net.Http;
using System.Net;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace AvaNet.Controllers
{
    public class ForumThreadsController : Controller
    {

        private readonly IForumThreadRepository forumThreadRepository;

        private readonly IForumTopicRepository forumTopicRepository;

        private readonly IForumLikeRepository forumLikeRepository;

        private readonly IPinnedForumThreadsRepository pinnedForumThreadsRepository;

        private readonly UserManager<ApplicationUser> userManager;

        private readonly HtmlSanitizer htmlSanitizer;

        public ForumThreadsController(HtmlSanitizer htmlSanitizer, IPinnedForumThreadsRepository pinnedForumThreadsRepository, IForumLikeRepository forumLikeRepository, IForumTopicRepository forumTopicRepository, IForumThreadRepository forumThreadRepository, UserManager<ApplicationUser> userManager)
        {
            this.pinnedForumThreadsRepository = pinnedForumThreadsRepository;
            this.forumThreadRepository = forumThreadRepository;
            this.forumTopicRepository = forumTopicRepository;
            this.forumLikeRepository = forumLikeRepository;
            this.userManager = userManager;
            this.htmlSanitizer = htmlSanitizer;
        }

        public IActionResult NavigateThreads(int ID, int startIndex, string orderBy)
        {
            ForumTopic forumTopic = forumTopicRepository.Find(ID, true);
            int updatedStartIndex = ForumThreadsIndexViewModel.GetStartIndex(startIndex, forumTopic.ForumThreads.Count);
            return Redirect("/ForumThreads/Index/" + ID + "?startIndex=" + updatedStartIndex + "&orderBy=" + orderBy);
        }

        public IActionResult NavigateComments(int ID, int startIndex, string orderBy)
        {
            ForumThread forumThread = forumThreadRepository.Find(ID, true);
            int updatedStartIndex = ForumThreadsIndexViewModel.GetStartIndex(startIndex, forumThread.ForumComments.Count);
            return Redirect("/ForumThreads/Details/" + ID + "?startIndex=" + updatedStartIndex + "&orderBy=" + orderBy);
        }

        public IActionResult Index(int ID, int startIndex, string orderBy)
        {
            ForumTopic forumTopic = forumTopicRepository.Find(ID, true);
            PinnedForumThreads pinnedForumThreads = pinnedForumThreadsRepository.Find(true);

            ForumThreadsIndexViewModel viewModel = new ForumThreadsIndexViewModel();
            viewModel.ForumTopicID = forumTopic.ForumTopicID;
            viewModel.ForumTopicTitle = forumTopic.Title;
            viewModel.PinnedForumThreads = pinnedForumThreads;

            //Set URL parameter values
            viewModel.StartIndex = startIndex;
            viewModel.OrderBy = orderBy;

            //Check to see if the user has altered the query parameter.
            if (startIndex % ForumThreadsIndexViewModel.NUMBER_OF_THREADS_PER_PAGE != 0)
            {
                return Redirect("/ForumThreads/Index/" + ID + "?startIndex=0&orderBy=newest"); 
            }
            if (!ForumThreadsIndexViewModel.IsStartIndexInRange(startIndex, forumTopic.ForumThreads.Count))
            {
                return Redirect("/ForumThreads/Index/" + ID + "?startIndex=0&orderBy=newest");
            }
            
            //No current user input of how to order threads
            if (orderBy == null)
            {
                viewModel.ForumThreads = forumTopic.ForumThreads
                    .OrderByDescending(t => t.ForumThreadCreationTime)
                    .Skip(viewModel.StartIndex)
                    .Take(ForumThreadsIndexViewModel.NUMBER_OF_THREADS_PER_PAGE);
            }
            else if (orderBy.Equals("mostLikes"))
            {
                viewModel.ForumThreads = forumTopic.ForumThreads
                    .OrderByDescending(t => t.ForumLikes.Sum(e => e.Weight))
                    .Skip(viewModel.StartIndex)
                    .Take(ForumThreadsIndexViewModel.NUMBER_OF_THREADS_PER_PAGE);
            }
            else if (orderBy.Equals("mostComments"))
            {
                viewModel.ForumThreads = forumTopic.ForumThreads
                    .OrderByDescending(t => t.ForumComments.Count)
                    .Skip(viewModel.StartIndex)
                    .Take(ForumThreadsIndexViewModel.NUMBER_OF_THREADS_PER_PAGE);
            }
            else if (orderBy.Equals("newest"))
            {
                viewModel.ForumThreads = forumTopic.ForumThreads
                    .OrderByDescending(t => t.ForumThreadCreationTime)
                    .Skip(viewModel.StartIndex)
                    .Take(ForumThreadsIndexViewModel.NUMBER_OF_THREADS_PER_PAGE);
            }
            
            return View(viewModel);
        }

        // GET: /<controller>/
        public IActionResult Details(int ID, int startIndex, string orderBy)
        {
            ForumThread forumThread = forumThreadRepository.Find(ID, true);

            //Check to see if the user has altered the query parameter.
            if (startIndex % ForumThreadsDetailsViewModel.NUMBER_OF_COMMENTS_PER_PAGE != 0)
            {
                return Redirect("/ForumThreads/Details/" + ID + "?startIndex=0&orderBy=newestComments");
            }
            if (!ForumThreadsDetailsViewModel.IsStartIndexInRange(startIndex, forumThread.ForumComments.Count))
            {
                return Redirect("/ForumThreads/Details/" + ID + "?startIndex=0&orderBy=oldestComments");
            }

            ForumThreadsDetailsViewModel viewModel = new ForumThreadsDetailsViewModel();
            viewModel.ForumThread = forumThread;
            viewModel.StartIndex = startIndex;
            viewModel.OrderBy = orderBy;

            if (orderBy == null)
            {
                viewModel.ForumThread.ForumComments = viewModel.ForumThread.ForumComments
                    .OrderBy(t => t.ForumCommentCreationTime)
                    .Skip(viewModel.StartIndex)
                    .Take(ForumThreadsDetailsViewModel.NUMBER_OF_COMMENTS_PER_PAGE)
                    .ToList();
            }
            else if (orderBy.Equals("oldestComments"))
            {
                viewModel.ForumThread.ForumComments = viewModel.ForumThread.ForumComments
                    .OrderBy(t => t.ForumCommentCreationTime)
                    .Skip(viewModel.StartIndex)
                    .Take(ForumThreadsDetailsViewModel.NUMBER_OF_COMMENTS_PER_PAGE)
                    .ToList();
            }
            else if (orderBy.Equals("newestComments"))
            {
                viewModel.ForumThread.ForumComments = viewModel.ForumThread.ForumComments
                    .OrderByDescending(t => t.ForumCommentCreationTime)
                    .Skip(viewModel.StartIndex)
                    .Take(ForumThreadsDetailsViewModel.NUMBER_OF_COMMENTS_PER_PAGE)
                    .ToList();
            }

            return View(viewModel);
        }

        //Called when the user is not logged in
        public IActionResult Create()
        {
            return Redirect("/");
        }
        
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title, Content, ForumTopicID")] ForumThread forumThread)
        {
            //Convert any new line characters.
            forumThread.Content = forumThread.Content.Replace("\r\n", "<br />");

            //Security check, allow desired html tags and remove malicious ones
            forumThread.Content = htmlSanitizer.RemoveUnwantedTags(forumThread.Content);
            // Generate the token and send it
            ApplicationUser user = await GetCurrentUserAsync();
            
            //Set creator of forum thread
            forumThread.ApplicationUser = user;
            forumThread.ForumThreadCreationTime = DateTime.UtcNow;
            forumThreadRepository.Add(forumThread);

            return Redirect("/ForumThreads/Details/" + forumThread.ForumThreadID);
        }

        [Authorize(Roles = "Administrator,Moderator")]
        public async Task<IActionResult> Ban(int ID)
        {
            // Generate the token and send it
            ApplicationUser user = await GetCurrentUserAsync();
            ForumThread forumThread = forumThreadRepository.Find(ID, false);

            forumThread.IsBanned = true;
            forumThreadRepository.Update(forumThread);
            return Redirect("/ForumThreads/Index/");
        }

        [Authorize(Roles = "Administrator,Moderator")]
        public async Task<IActionResult> Remove(int ID)
        {
            // Generate the token and send it
            ApplicationUser user = await GetCurrentUserAsync();
            forumThreadRepository.Remove(ID);
            return Redirect("/");
        }

        private async Task<ApplicationUser> GetCurrentUserAsync()
        {
            return await userManager.GetUserAsync(HttpContext.User);
        }
    }
}

TaccomStrike.Web/Views/ForumThreads/Index.cshtml
@model AvaNet.Models.ViewModels.ForumViewModels.ForumThreadsIndexViewModel
@using Microsoft.AspNetCore.Identity
@using AvaNet.Services

@inject DateFormatter DateFormatter
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<div class="row">
    <div class="col-md-6">
        <div id="forumTopicTitle2">@Model.ForumTopicTitle</div>
    </div>
    <div class="col-md-4">
        <div class="forumThreadOrderByPanel">
            <div class="gap"></div>
            <a asp-action="Index" asp-controller="ForumThreads" asp-route-id="@Model.ForumTopicID" asp-route-orderBy="mostLikes">
                <div class="forumThreadOrderByOption">
                    Most Likes
                </div>
            </a>
            <a asp-action="Index" asp-controller="ForumThreads" asp-route-id="@Model.ForumTopicID" asp-route-orderBy="mostComments">
                <div class="forumThreadOrderByOption">
                    Most Comments
                </div>
            </a>
            <a asp-action="Index" asp-controller="ForumThreads" asp-route-id="@Model.ForumTopicID" asp-route-orderBy="newest">
                <div class="forumThreadOrderByOption">
                    Newest
                </div>
            </a>
        </div>
    </div>
    @if (Model.ForumTopicTitle.Equals("Game News and Updates"))
    {
        @if (SignInManager.IsSignedIn(User))
        {
            if (User.IsInRole("Administrator") || User.IsInRole("Moderator"))
            {
                <div class="col-md-2">
                    <div id="forumThreadCreateButton">+ New Thread</div>
                </div>
            }
        }
    }
    else
    {
        <div class="col-md-2">
            <div id="forumThreadCreateButton">+ New Thread</div>
        </div>
    }
</div>
<div class="gapFour"></div>

<form class="form-group" id="forumThreadForm" asp-action="Create" asp-controller="ForumThreads">
    <div class="row">
        <div class="form-group col-md-3">
            <div id="forumThreadFormTitleLabel">Thread Title:</div>
        </div>
        <div class="form-group col-md-8">
            <input name="Title" class="form-control" maxlength="60" />
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-3">
            <div id="forumThreadFormContentLabel">Thread Content:</div>
        </div>
        <div class="form-group col-md-8">
            <textarea id="forumThreadFormContentInput" maxlength="1800" name="Content" class="form-control"></textarea>
        </div>
    </div>
    <input type="hidden" name="ForumTopicID" value="@Model.ForumTopicID">
    <div class="row">
        <div class="form-group col-md-3"></div>
        <div class="form-group col-md-3">
            <input id="forumThreadFormSubmit" type="submit" value="Submit Thread" />
        </div>
        <div class="form-group col-md-1"></div>
        <div class="form-group col-md-3">
            <div id="forumThreadCloseButton">Close</div>
        </div>
        <div class="form-group col-md-2"></div>
    </div>
</form>

<hr />

@foreach (ForumThread pinnedForumThread in Model.PinnedForumThreads.ForumThreads)
{
    int likeCount = 0;

    foreach (ForumLike fl in pinnedForumThread.ForumLikes)
    {
        likeCount += fl.Weight;
    }

    <div class="row">
        <div class="col-md-12">
            <a asp-action="Details" asp-route-id="@pinnedForumThread.ForumThreadID" asp-controller="ForumThreads">
                <div class="forumThreadPanel admin">
                    <div class="row">
                        <div class="col-sm-7">
                            <div class="forumThreadPanelTitle">@Html.DisplayFor(modelItem => pinnedForumThread.Title)</div>
                        </div>
                        <div class="col-sm-3">
                            @if (UserManager.IsInRoleAsync(pinnedForumThread.ApplicationUser, "Administrator").Result || UserManager.IsInRoleAsync(pinnedForumThread.ApplicationUser, "Moderator").Result)
                            {
                                <div class="forumThreadPanelLabel admin">
                                    Posted by: @Html.DisplayFor(modelItem => pinnedForumThread.ApplicationUser.GameUserID)
                                </div>
                            }
                            else
                            {
                                <div class="forumThreadPanelLabel">
                                    Posted by: @Html.DisplayFor(modelItem => pinnedForumThread.ApplicationUser.GameUserID)
                                </div>
                            }
                        </div>
                        <div class="col-sm-2">
                            <div class="forumThreadPanelLabel">
                                @DateFormatter.GetTimeAgo(pinnedForumThread.ForumThreadCreationTime)
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-5 col-sm-4 col-md-2">
                            <div class="forumThreadPanelLikeImage"></div>
                            <div class="forumThreadPanelLikeLabel">@likeCount</div>
                        </div>
                        <div class="col-xs-5 col-sm-4 col-md-2">
                            <div class="forumThreadPanelCommentsImage"></div>
                            <div class="forumThreadPanelCommentsLabel">@pinnedForumThread.ForumComments.Count</div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>
}

<div id="forumThreadsNavigationDivider">
    <div class="gap"></div>
    <div class="gap"></div>
</div>

@foreach (ForumThread item in Model.ForumThreads)
{
    ApplicationUser currentUser = UserManager.GetUserAsync(User).Result;
    int likeCount = 0;

    foreach (ForumLike fl in item.ForumLikes)
    {
        likeCount += fl.Weight;
    }

    <div class="row">
        <div class="col-md-12">
            <a asp-action="Details" asp-route-id="@item.ForumThreadID" asp-controller="ForumThreads">
                <div class="forumThreadPanel">
                    <div class="row">
                        <div class="col-sm-7">
                            <div class="forumThreadPanelTitle">@Html.DisplayFor(modelItem => item.Title)</div>
                        </div>
                        <div class="col-sm-3">
                            @if (UserManager.IsInRoleAsync(item.ApplicationUser, "Administrator").Result || UserManager.IsInRoleAsync(item.ApplicationUser, "Moderator").Result)
                            {
                                <div class="forumThreadPanelLabel admin">
                                    Posted by: @Html.DisplayFor(modelItem => item.ApplicationUser.GameUserID)
                                </div>
                            }
                            else
                            {
                                <div class="forumThreadPanelLabel">
                                    Posted by: @Html.DisplayFor(modelItem => item.ApplicationUser.GameUserID)
                                </div>
                            }
                        </div>
                        <div class="col-sm-2">
                            <div class="forumThreadPanelLabel">
                                @DateFormatter.GetTimeAgo(item.ForumThreadCreationTime)
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-5 col-sm-4 col-md-2">
                            <div class="forumThreadPanelLikeImage"></div>
                            <div class="forumThreadPanelLikeLabel">@likeCount</div>
                        </div>
                        <div class="col-xs-5 col-sm-4 col-md-2">
                            <div class="forumThreadPanelCommentsImage"></div>
                            <div class="forumThreadPanelCommentsLabel">@item.ForumComments.Count</div>
                        </div>
                    </div>
                </div>
            </a>
            @if (SignInManager.IsSignedIn(User))
            {
                if (UserManager.IsInRoleAsync(currentUser, "Administrator").Result || UserManager.IsInRoleAsync(currentUser, "Moderator").Result)
                {
                    <div class="row">
                        <div class="col-md-6">
                            <a asp-action="Ban" asp-controller="ForumThreads" asp-route-id="@item.ForumThreadID">Ban Thread</a>
                        </div>
                        <div class="col-md-6">
                            <a asp-action="Remove" asp-controller="ForumThreads" asp-route-id="@item.ForumThreadID">Delete Thread</a>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
}

<div id="forumThreadsNavigationDivider">
    <div class="gap"></div>
</div>

<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div id="forumThreadsNavigationPanel">
            <a asp-action="NavigateThreads" asp-controller="ForumThreads" asp-route-id="@Model.ForumTopicID" asp-route-orderBy="@Model.OrderBy" asp-route-startIndex="@Model.GetPreviousStartIndex()">
                <div id="forumThreadsNavigationLeft" class="forumThreadsNavigation"></div>
            </a>
            <a asp-action="NavigateThreads" asp-controller="ForumThreads" asp-route-id="@Model.ForumTopicID" asp-route-orderBy="@Model.OrderBy" asp-route-startIndex="@Model.GetNextStartIndex()">
                <div id="forumThreadsNavigationRight" class="forumThreadsNavigation"></div>
            </a>
        </div>
    </div>
    <div class="col-md-3"></div>
</div>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script>
    $("#forumThreadCreateButton").click(function () {
        $("#forumThreadForm").slideDown();
    });
    $("#forumThreadCloseButton").click(function () {
        $("#forumThreadForm").slideUp();
    });
</script>